### ISSUE TITLE
Setting project specific classpaths for JDTLS

### ISSUE THREAD

**Issue by edvardfagerholmsc** [zed-extensions/java#10]
I have a large Java project that spans multiple git submodules. With IntelliJ there's a large config file which pieces together all the stuff to add to the classpath. I don't see any ability to easily configure the classpath using this Java plugin.

**Comment by valentinegb** [comment]
Can you please try out the `classpath` branch and let me know if it works good for you?

**Comment by edvardfagerholmsc** [comment]
Not sure what the correct way to solve this should be. I'm seeing the following warnings in the IDE:

1. The declared package does not match the expected package
2. Imports do not resolve

My current config is the following:

```
{
  "lsp": {
    "jdtls": {
      "settings": {
        "java_home": "/Library/Java/JavaVirtualMachines/temurin-21.jdk/Contents/Home",
        "classpath": "~/git/xxx/build/server/realtime/src"
      }
    }
  }
}
```

To tackle the first problem, so I have the class `Foo.java` inside `~/git/xxx/build/server/realtime/src/xxx/yyy` and `package xxx.yyy` is then considered an invalid package name by the editor. The folder that I've opened in the server is `~/git/xxx/build/server`, which is the Gradle root for the server part of my project and what we open in Eclipse/IDEA.

An unrelated question, since it's my first time trying out Zed. In the classpath above I'm using a $HOME relative directory for setting the classpath. However, in a large project, I would like to check in the project specific Zed configuration and people will have the project checked out in different locations. How could I set the classpath variables relative to the project root?

**Comment by valentinegb** [comment]
> How could I set the classpath variables relative to the project root?

I could be wrong, but I don't think Zed exposes an environment variable for the workspace root in settings (it does for tasks, but that doesn't help here). However, JDTLS is started with the working directory being the workspace root, so then I think a relative path (`./`) would start from there in the class path.

> Not sure what the correct way to solve this should be.

I'm going to have to get back to you on that, I'm going to do some more testing.

**Comment by valentinegb** [comment]
There might be an initialization option that would help, you should check the `README.md` in the initialization-options branch (initialization options already work in all branches, just wasn't explained until that new branch)

**Comment by valentinegb** [comment]
I'm marking this as resolved since I *have* added a `classpath` setting, but if you're still having issues feel free to comment here or in a new issue.
