### ISSUE TITLE
Language server error: jdtls  wasm trap: cannot enter component instance

### ISSUE THREAD

**Issue by edwloef** [zed-extensions/java#18]

**Comment by valentinegb** [comment]
Could you give any more information?

**Comment by edwloef** [comment]
Not really... I had a few times where Zed failed to download the jdtls, probably because it took too long, and once it managed to do that it still fails to start it, with this error message. If there's any more debugging I can do please let me know :)

**Comment by valentinegb** [comment]
Could you try letting JDTLS download and then after it fails, open Zed logs using the command palette (<kbd>shift</kbd> <kbd>command</kbd> <kbd>P</kbd> on Mac) and send the log?

**Comment by edwloef** [comment]
I'm sadly unable to reproduce this anymore, even on my slow uni wifi (~4.6 Mbit/s). Maybe the download just corrupted yesterday, and the issue has since resolved itself?

Should I close the issue in this case?
