### ISSUE TITLE
Release lombok support

### ISSUE THREAD

**Issue by t40mas** [zed-extensions/java#19]
Hey everyone, when will the next version with Lombok support be released?

**Comment by valentinegb** [comment]
... As soon as https://github.com/zed-industries/extensions/pull/1615 is pulled!

(Super sorry about that, I got busy with other stuff ^^')

**Comment by inad9300** [comment]
@valentinegb how can this feature be enabled? I'm struggling to follow the instructions in the README file. In particular, I'm confused about the different paths used by the different examples:
- `          initialization_options.settings.java.jdt.ls.lombokSupport.enabled`
- `lsp.jdtls.initialization_options.settings.java       .lombokSupport.enabled`
- `lsp.jdtls                       .settings            .lombok_version`

Would you mind adding a full example of a `.../zed/settings.json` file that enables Lombok support?

Thank you!

**Comment by inad9300** [comment]
> Would you mind adding a full example of a `.../zed/settings.json` file that enables Lombok support?

Answering my own question, I managed to get it working through a combination of the first two options, i.e.
```json
{
  "lsp": {
    "jdtls": {
      "initialization_options": {
        "settings": {
          "java": {
            "jdt": {
              "ls": {
                "lombokSupport": { "enabled": true }
              }
            }
          }
        }
      }
    }
  }
}
```

What a mouthful!

It'd be great to fix/clarify the documentation nonetheless. (And, ideally, to simplify it a bit :see_no_evil:)

**Comment by valentinegb** [comment]
> What a mouthful!

Yeah sorry about that ^^'
Unfortunately, the initialization options *aren't* determined by the extension, they're passed right to the language server. So to change them at all, you'll have to bring it up with [those guys](https://github.com/eclipse-jdtls/eclipse.jdt.ls).
