### ISSUE TITLE
Partially import maven projects

### ISSUE THREAD

**Issue by quackerex** [zed-extensions/java#21]
Similar to how VSCode Java extension does it 

<img width="889" alt="Screenshot" src="https://github.com/user-attachments/assets/92f575eb-4c82-4633-9a8e-725908a7cc85">
<img width="372" alt="Screenshot" src="https://github.com/user-attachments/assets/794969ea-5d12-45f6-8acd-d56988e0d888">
<img width="628" alt="Screenshot" src="https://github.com/user-attachments/assets/fb4e555e-96e7-4fc0-a26d-51fc4ed0d2a6">

**Comment by valentinegb** [comment]
Zed extensions are not currently able to present dialogues, like in the second and third images you showed. How necessary is this functionality?

**Comment by quackerex** [comment]
My current use case is I don't have all the deps set up to import all of them. So I can only import the parts I work on so I get code completions and debugging support.

**Comment by valentinegb** [comment]
If you configure [`lsp.jdtls. initialization_options.settings.java.import.exclusions`](https://github.com/eclipse-jdtls/eclipse.jdt.ls/wiki/Running-the-JAVA-LS-server-from-the-command-line#initialize-request) for your project, does that do what you want?

**Comment by valentinegb** [comment]
Just want to follow up, did my last comment resolve the issue?
