### ISSUE TITLE
Bug ? Why does it produce files?

### ISSUE THREAD

**Issue by francois-pasquier** [zed-extensions/java#22]
In my project (react native so the java files are segregated to apps/native/android), I have some files that are created when I run zed with this extension.
e.g:

	new file:   apps/native/android/.project
	new file:   apps/native/android/.settings/org.eclipse.buildship.core.prefs
	new file:   apps/native/android/app/.classpath
	new file:   apps/native/android/app/.project
	new file:   apps/native/android/app/.settings/org.eclipse.buildship.core.prefs
	new file:   apps/native/android/calendar_range_picker/.classpath
	new file:   apps/native/android/calendar_range_picker/.project
	new file:   apps/native/android/calendar_range_picker/.settings/org.eclipse.buildship.core.prefs
	new file:   apps/native/android/rvgenadapter/.classpath
	new file:   apps/native/android/rvgenadapter/.project
	new file:   apps/native/android/rvgenadapter/.settings/org.eclipse.buildship.core.prefs
	
Is it an expected behaviour?

**Comment by valentinegb** [comment]
I believe so, but you would have to ask the [JDTLS](https://github.com/eclipse-jdtls/eclipse.jdt.ls) developers to be 100% certain.
