### ISSUE TITLE
Add 'Go to Definition' Support for JDK and External Dependency.

### ISSUE THREAD

**Issue by marques-gabriel** [zed-extensions/java#23]
Hello,

I am currently testing the Zed editor with Java Projects using `Maven`. While the "Go to Definition" functionality works well for classes defined within my project, it does not work for classes from the JDK (e.g., `System`) or from external dependencies.

**Steps to Reproduce:**
1. Open a Java project in Zed with the `JDTLS` enabled.
2. Try to use "Go to Definition" on a JDK class (e.g., `System`) or a class/JAR from an external dependency.

**Expected Behavior:**
The editor should navigate to the definition of the class, whether it is part of the JDK or an external dependency.

**Actual Behavior:**
The editor does not navigate to the definition of JDK classes or classes/JAR from external dependencies.

It would be greatly appreciated if this functionality could be added to improve the development experience, for efficient navigation and understanding of the code, especially when working with complex projects that rely heavily on external libraries.

Thank you for your attention to this matter.

**Comment by valentinegb** [comment]
Unfortunately, this is not currently possible in Zed. [Eclipse JDT Language Server], the language server that this Zed extension uses, implements various features while taking advantage of LSP[^1] extensions, which are additions to standard LSP[^1], and this is one of those features. Zed extensions do not implement LSP[^1] themselves, Zed itself does that, and Zed itself only implements (as far as I'm aware) standard LSP.

So, in its current form and with Zed's current capabilities, this is unfortunately not possible, although I do hope that it is possible eventually. I talked more about this in #20.

[^1]: Language Server Protocol

[Eclipse JDT Language Server]: https://github.com/eclipse-jdtls/eclipse.jdt.ls

**Comment by valentinegb** [comment]
I opened an issue related to this for Zed, you should watch it: https://github.com/zed-industries/zed/issues/21133

**Comment by thrasosc** [comment]
This is the only missing feature preventing me from moving to Zed.
