### ISSUE TITLE
The Java home setting does not change the JDK used to start the server

### ISSUE THREAD

**Issue by nulliver** [zed-extensions/java#24]
### What happened?

My `$JAVA_HOME` environment variable points to JDK 8 because I'm working on several projects that require Java 8. Since JDTLS requires Java 17+, I added the following to my Zed configuration:

```json
{
  "lsp": {
      "jdtls": {
        "initialization_options": {
          "settings": {
            "java": {
              "home": "/Users/username/.sdkman/candidates/java/21.0.4-tem"
            }
          }
        }
      }
  }
}
```

but it doesn't work, it throws the following error, seems that it's still using the `$JAVA_HOME` version:
```text
Language server error: jdtls

oneshot canceled
-- stderr--
Traceback (most recent call last):
  File "/Users/username/Library/Application Support/Zed/extensions/work/java/jdt-language-server-1.40.0/bin/jdtls", line 17, in <module>
    jdtls.main(sys.argv[1:])
    ~~~~~~~~~~^^^^^^^^^^^^^^
  File "/Users/username/Library/Application Support/Zed/extensions/work/java/jdt-language-server-1.40.0/bin/jdtls.py", line 87, in main
    java_executable = get_java_executable(known_args)
  File "/Users/username/Library/Application Support/Zed/extensions/work/java/jdt-language-server-1.40.0/bin/jdtls.py", line 44, in get_java_executable
    raise Exception("jdtls requires at least Java 17")
Exception: jdtls requires at least Java 17
```
If I change my `$JAVA_HOME` to Java 21, the plugin starts the server correctly.

If I start the server directly with the following command, the server starts fine, it uses the `-Djava.home` argument I pass instead of the `$JAVA_HOME` environment variable so I don't think it's a JDTLS issue:
```shell
java \
-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=1044 \
-Djava.home=/Users/username/.sdkman/candidates/java/21.0.4-tem \
-Declipse.application=org.eclipse.jdt.ls.core.id1 \
-Dosgi.bundles.defaultStartLevel=4 \
-Declipse.product=org.eclipse.jdt.ls.core.product \
-Dlog.protocol=true -Dlog.level=ALL -Xmx1G \
-jar "/Users/username/Library/Application Support/Zed/extensions/work/java/jdt-language-server-1.40.0/plugins/org.eclipse.equinox.launcher_1.6.900.v20240613-2009.jar" \
-configuration ./config_mac -data /Users/username/code/java-project
```

I was able to reproduce this in two computers: a M3 MacBook Pro (macOS Sequoia) and an M1 MacBook Pro (macOS Sonoma).

Am I configuring the wrong setting? 

### What did you expect to happen?

The plugin should start JDTLS using the `lsp.jdtls.initialization_options.settings.java.home` as specified in the README.

**Comment by valentinegb** [comment]
Everything from `lsp.jdtls.initialization_options` onwards is sent straight to the language server, so any peculiarities can be attributed to JDTLS and not the Zed Java extension. The extension only handles `lsp.jdtls.settings`.

**Comment by valentinegb** [comment]
I should note, though, that `lsp.jdtls.initialization_options.settings.java.home` is meant to be the version of Java to use for the *project*, not for JDTLS.

**Comment by nulliver** [comment]
Understood. Is there a way to use a different version of Java to start the server instead of it using `$JAVA_HOME`?

**Comment by valentinegb** [comment]
I believe you could launch Zed from a terminal with `JAVA_HOME=/path/to/java21 zed`. I would recommend giving [Zed's documentation](https://zed.dev/docs/environment#where-does-zed-get-its-environment-variables-from) a look.

**Comment by valentinegb** [comment]
Alright, that all sounds reasonable to me. I’ll get that implemented when I can :+1:
