### ISSUE TITLE
Caret not indented properly when enter is pressed

### ISSUE THREAD

**Issue by Shubham076** [zed-extensions/java#30]
### What happened?

Caret not indented properly with new line character
Current:
[
<img width="728" alt="Screenshot 2024-12-29 at 8 20 16 PM" src="https://github.com/user-attachments/assets/6aa90b90-e6fa-4358-8874-ccec71706345" />
](url)

### What did you expect to happen?

Expected:
<img width="640" alt="Screenshot 2024-12-29 at 8 22 24 PM" src="https://github.com/user-attachments/assets/d56f7adb-2289-44e9-9f13-ee584f4c7221" />

**Comment by valentinegb** [comment]
Can you send the language server RPC log immediately after autocompleting? You should enable the RPC log before autocompleting, IIRC you have to click Log Level. (Search for something like "language server: open log" in the command palette.)

**Comment by valentinegb** [comment]
Could you please try downloading the [`indents-rewrite`](https://github.com/zed-extensions/java/tree/indents-rewrite) branch and using the `zed: install dev extension` command in Zed to test it?

**Comment by Shubham076** [comment]
> Can you send the language server RPC log immediately after autocompleting? You should enable the RPC log before autocompleting, IIRC you have to click Log Level. (Search for something like "language server: open log" in the command palette.)
> 
> Edit: sorry, that is all assuming you autocompleted the method in your screenshot, could you please clarify if you mean just after pressing enter?

yes its just pressing enter no autocomplete

**Comment by Shubham076** [comment]
> Could you please try downloading the [`indents-rewrite`](https://github.com/zed-extensions/java/tree/indents-rewrite) branch and using the `zed: install dev extension` command in Zed to test it?

not familiar with rust dev setup right now, can you help with any documentation on how to build, post checkout to this branch?

**Comment by Shubham076** [comment]
> Could you please try downloading the [`indents-rewrite`](https://github.com/zed-extensions/java/tree/indents-rewrite) branch and using the `zed: install dev extension` command in Zed to test it?

tested on local working fine
