### ISSUE TITLE
extension says that it cannot find JDTLS in PATH

### ISSUE THREAD

**Issue by adhi-thirumala** [zed-extensions/java#8]
Hi,
What specifically do I make PATH point towards? Is it a folder in the JDTLS repo after I build it? How specifically do I "install" JDTLS? I am on Fedora 41 for reference.

**Comment by valentinegb** [comment]
You can download the latest milestone build [here](https://www.eclipse.org/downloads/download.php?file=/jdtls/milestones/1.40.0/jdt-language-server-1.40.0-202409261450.tar.gz), then you want to make sure that `./bin/jdtls` is in your `PATH`.

**Comment by valentinegb** [comment]
I will assume that this is resolved, but please feel free to say something if you're still having trouble.
